package main

import (
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/konsulin-care/konsulin-app/internal/data/wilayah"
)

// outputPath is the path where data.go is written.
// The Go generate tool runs in the package directory, so a bare filename is correct.
// Overridden in tests.
var outputPath = "data.go"

func main() {
	if err := runGenerate(); err != nil {
		log.Fatalf("Generation failed: %v", err)
	}
}

// writeDataFile writes the complete WilayahIndex literal to disk.
//
//nolint:gosec // outputPath is a known constant path, not user input.
func writeDataFile(idx wilayah.WilayahIndex) error {
	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer func() { _ = f.Close() }()

	const baseURL = "https://github.com/emsifa/api-wilayah-indonesia/archive/refs/heads/master.zip"

	_, err = fmt.Fprintf(f, `// Code generated by go:generate; DO NOT EDIT.

package wilayah

// WilayahData is the pre-built index of all Indonesia administrative regions.
// Generated from %s
var WilayahData = WilayahIndex{
	Provinces: []Province{
%s
	},
	Regencies: []Regency{
%s
	},
	Districts: []District{
%s
	},
	Villages: []Village{
%s
	},
	ProvinceByID: map[string]int{
%s
	},
	RegencyByID: map[string]int{
%s
	},
	DistrictByID: map[string]int{
%s
	},
	VillageByID: map[string]int{
%s
	},
	RegenciesByProvince: map[string][]int{
%s
	},
	DistrictsByRegency: map[string][]int{
%s
	},
	VillagesByDistrict: map[string][]int{
%s
	},
	ProvinceByName: map[string][]int{
%s
	},
	RegencyByName: map[string][]int{
%s
	},
	DistrictByName: map[string][]int{
%s
	},
	VillageByName: map[string][]int{
%s
	},
}
`, baseURL,
		formatProvinceLiterals(idx.Provinces),
		formatRegencyLiterals(idx.Regencies),
		formatDistrictLiterals(idx.Districts),
		formatVillageLiterals(idx.Villages),
		formatStringIntMap(idx.ProvinceByID),
		formatStringIntMap(idx.RegencyByID),
		formatStringIntMap(idx.DistrictByID),
		formatStringIntMap(idx.VillageByID),
		formatStringIntSliceMap(idx.RegenciesByProvince),
		formatStringIntSliceMap(idx.DistrictsByRegency),
		formatStringIntSliceMap(idx.VillagesByDistrict),
		formatStringIntSliceMap(idx.ProvinceByName),
		formatStringIntSliceMap(idx.RegencyByName),
		formatStringIntSliceMap(idx.DistrictByName),
		formatStringIntSliceMap(idx.VillageByName),
	)
	return err
}

func formatProvinceLiterals(provinces []wilayah.Province) string {
	var b strings.Builder
	for _, p := range provinces {
		fmt.Fprintf(&b, "\t\t{ID: %q, Name: %q},\n", p.ID, p.Name)
	}
	return strings.TrimRight(b.String(), "\n")
}

func formatRegencyLiterals(regencies []wilayah.Regency) string {
	var b strings.Builder
	for _, r := range regencies {
		fmt.Fprintf(&b, "\t\t{ID: %q, Name: %q, ProvinceID: %q},\n", r.ID, r.Name, r.ProvinceID)
	}
	return strings.TrimRight(b.String(), "\n")
}

func formatDistrictLiterals(districts []wilayah.District) string {
	var b strings.Builder
	for _, d := range districts {
		fmt.Fprintf(&b, "\t\t{ID: %q, Name: %q, RegencyID: %q},\n", d.ID, d.Name, d.RegencyID)
	}
	return strings.TrimRight(b.String(), "\n")
}

func formatVillageLiterals(villages []wilayah.Village) string {
	var b strings.Builder
	for _, v := range villages {
		fmt.Fprintf(&b, "\t\t{ID: %q, Name: %q, DistrictID: %q},\n", v.ID, v.Name, v.DistrictID)
	}
	return strings.TrimRight(b.String(), "\n")
}

func formatStringIntMap(m map[string]int) string {
	var b strings.Builder
	for k, v := range m {
		fmt.Fprintf(&b, "\t\t%q: %d,\n", k, v)
	}
	return strings.TrimRight(b.String(), "\n")
}

func formatStringIntSliceMap(m map[string][]int) string {
	var b strings.Builder
	for k, v := range m {
		values := make([]string, len(v))
		for i, vi := range v {
			values[i] = fmt.Sprintf("%d", vi)
		}
		fmt.Fprintf(&b, "\t\t%q: {%s},\n", k, strings.Join(values, ", "))
	}
	return strings.TrimRight(b.String(), "\n")
}
