.PHONY: deps test-go test-js test fmt-go check-fmt-go check-file-length
.PHONY: lint-go-cognitive lint-go check-go dev dev-go dev-next serve build-next
.PHONY: build-go run docker-check

# Dependencies
deps:
	npm ci
	go mod download

# Testing
test-go:
	go test ./... -count=1

test-js:
	npm run test:run

test: test-go test-js

# Go formatting
fmt-go:
	gofmt -s -w ./cmd/ ./internal/

check-fmt-go:
	@! gofmt -s -d ./cmd/ ./internal/ | read i; \
	echo "  Go formatting is correct ✓"

# Go file length check (staged files only)
check-file-length:
	@git diff --cached --name-only --diff-filter=ACMR | grep '\.go$$' | while read f; do \
	  if [ -f "$$f" ] && [ "$$(head -1 "$$f")" = "// Code generated by go:generate; DO NOT EDIT." ]; then \
	    continue; \
	  fi; \
	  if [ -f "$$f" ] && [ "$$(wc -l < "$$f")" -gt 300 ]; then \
	    echo "FAIL: $$f has $$(wc -l < "$$f") lines (max 300)"; \
	    exit 1; \
	  fi; \
	done
	@echo "  Staged Go files under 300 lines ✓"

# Go linting
lint-go-cognitive:
	@gocognit -over 15 ./cmd ./internal 2>/dev/null; \
	if [ $$? -eq 1 ]; then \
	  echo "FAIL: cognitive complexity > 15 detected"; \
	  gocognit -over 15 ./cmd ./internal; \
	  exit 1; \
	fi
	@echo "  Cognitive complexity ≤ 15 ✓"

lint-go:
	golangci-lint run ./...

check-go: check-file-length lint-go-cognitive check-fmt-go lint-go
	go vet ./...

# Dockerfile linting
docker-check:
	if command -v hadolint >/dev/null 2>&1; then \
	  hadolint Dockerfile; \
	else \
	  echo "  hadolint not available (run mise install)"; \
	fi

# Build Next.js static export
build-next:
	npm run build

# Ports
GO_PORT ?= 3000
NEXT_PORT ?= 8000

# Development: hot reload mode (Next.js dev server + Go BFF proxy)
dev:
	@rm -rf out .next
	@echo "Go BFF on :$(GO_PORT)  |  Next.js on :$(NEXT_PORT)"
	@trap 'kill 0' EXIT; \
	  export PORT=$(GO_PORT) APP_URL=http://localhost:$(GO_PORT) API_URL=$${API_URL:-http://localhost:3200} TX_URL=$${TX_URL:-http://localhost:3300} NEXTJS_URL=http://localhost:$(NEXT_PORT) SESSION_COOKIE_SECRET=$${SESSION_COOKIE_SECRET:-CHANGE_ME_generate_a_random_64_char_secret} CSRF_AUTH_KEY=$${CSRF_AUTH_KEY:-dev-csrf-auth-key-32-bytes-long!}; \
	  go run ./cmd/konsulin-app & \
	  npm run dev -- -p $(NEXT_PORT) & \
	  wait

# Go BFF only (requires NEXTJS_URL to proxy to Next.js)
dev-go:
	export PORT=$(GO_PORT) APP_URL=http://localhost:$(GO_PORT) API_URL=$${API_URL:-http://localhost:3200} TX_URL=$${TX_URL:-http://localhost:3300} NEXTJS_URL=http://localhost:$(NEXT_PORT) SESSION_COOKIE_SECRET=$${SESSION_COOKIE_SECRET:-CHANGE_ME_generate_a_random_64_char_secret} CSRF_AUTH_KEY=$${CSRF_AUTH_KEY:-dev-csrf-auth-key-32-bytes-long!}; \
	go run ./cmd/konsulin-app

# Next.js dev server standalone (open separate terminal)
dev-next:
	npm run dev -- -p $(NEXT_PORT)

# Production-like: build Next.js statically, then serve via Go BFF
serve: build-next
	@echo "Go BFF on :$(GO_PORT) serving static out/"
	@export PORT=$(GO_PORT) APP_URL=http://localhost:$(GO_PORT) API_URL=$${API_URL:-http://localhost:3200} TX_URL=$${TX_URL:-http://localhost:3200} SESSION_COOKIE_SECRET=$${SESSION_COOKIE_SECRET:-CHANGE_ME_generate_a_random_64_char_secret} CSRF_AUTH_KEY=$${CSRF_AUTH_KEY:-dev-csrf-auth-key-32-bytes-long!}; \
	  go run ./cmd/konsulin-app

# Build
build-go:
	go build -o konsulin-app ./cmd/konsulin-app

run:
	go run ./cmd/konsulin-app

data-wilayah:
	go generate ./internal/data/wilayah/

