export const questionList = [
  'Apa hal terbaik yang terjadi padaku hari ini?',
  'Apa hal yang membuatku tersenyum hari ini?',
  'Apa yang paling menantang bagiku hari ini?',
  'Apa makanan paling enak yang aku makan hari ini?',
  'Siapa orang yang paling berpengaruh dalam hariku hari ini?',
  'Apa yang aku pelajari hari ini?',
  'Apa hal kecil yang membuatku bahagia hari ini?',
  'Apa yang aku syukuri hari ini?',
  'Apa yang membuatku merasa damai hari ini?',
  'Apa momen terbaik dalam hariku hari ini?',
  'Apa yang membuatku tertawa hari ini?',
  'Apa yang aku pelajari tentang diriku sendiri hari ini?',
  'Apa yang aku syukuri tentang diriku sendiri hari ini?',
  'Apa kejadian paling menyenangkan yang aku alami hari ini?',
  'Apa yang aku lakukan untuk merawat diriku hari ini?',
  'Apa buku atau artikel yang paling menarik yang aku baca hari ini?',
  'Apa yang aku lakukan untuk orang lain hari ini?',
  'Apa yang aku syukuri tentang pekerjaanku hari ini?',
  'Apa yang membuatku merasa puas hari ini?',
  'Apa hal yang ingin aku ingat tentang hari ini?',
  'Apa yang membuatku merasa bangga pada diriku sendiri hari ini?',
  'Apa yang aku lakukan untuk menjaga kesehatan fisikku hari ini?',
  'Apa yang aku lakukan untuk menjaga kesehatan mentalku hari ini?',
  'Apa yang aku nikmati tentang alam hari ini?',
  'Apa tantangan terbesar yang aku hadapi hari ini?',
  'Apa yang membuatku merasa bersyukur tentang keluargaku hari ini?',
  'Apa yang membuatku merasa nyaman di rumah hari ini?',
  'Apa yang aku syukuri tentang teman-temanku hari ini?',
  'Apa yang membuatku merasa kreatif hari ini?',
  'Apa yang aku capai hari ini yang membuatku bangga?',
  'Apa yang aku rasakan tentang cuaca hari ini?',
  'Apa yang membuatku merasa bersemangat hari ini?',
  'Apa yang aku lakukan untuk bersantai hari ini?',
  'Apa yang aku pelajari tentang orang lain hari ini?',
  'Apa yang aku lakukan yang membuat orang lain bahagia hari ini?'
]
