package main

import (
	"fmt"
	"os"
	"time"
)

// OutputData represents the data to be written to output files.
type OutputData struct {
	GeneratedAt string
	Proximity   map[string]map[string]float64
	Index       map[string]*SpecialtyNodeOutput
}

// SpecialtyNodeOutput represents a specialty node for output.
type SpecialtyNodeOutput struct {
	NuccCode        string   `json:"nuccCode"`
	IscoCode        string   `json:"iscoCode"`
	Label           string   `json:"label"`
	DomainSignature []string `json:"domainSignature"`
}

// writeOutput writes the generated data to files.
func writeOutput(data *OutputData) error {
	// Write Go file
	if err := writeGoOutput(data); err != nil {
		return fmt.Errorf("writing Go output: %w", err)
	}

	// Write TypeScript file
	if err := writeTSOutput(data); err != nil {
		return fmt.Errorf("writing TypeScript output: %w", err)
	}

	return nil
}

// fromPackageDir reports whether the generator runs with the package directory
// as the working directory (true when invoked via `go generate`, which sets cwd
// to the package directory). It mirrors the existing os.Stat("config") detection.
func fromPackageDir() bool {
	_, err := os.Stat("config")
	return !os.IsNotExist(err)
}

func writeGoOutput(data *OutputData) error {
	total := len(data.Proximity)
	content := fmt.Sprintf(`// Code generated by go:generate; DO NOT EDIT.
// Generated at: %s

package specialty

// ProximityTable maps specialty pairs to their proximity scores.
type ProximityTable map[string]map[string]float64

// GeneratedProximity contains the pre-computed proximity data.
var GeneratedProximity = ProximityTable{
`, data.GeneratedAt)

	i := 0
	for codeA, row := range data.Proximity {
		content += fmt.Sprintf("\t%q: {\n", codeA)
		for codeB, score := range row {
			content += fmt.Sprintf("\t\t%q: %f,\n", codeB, score)
		}
		content += "\t},\n"
		i++
		if i%50 == 0 || i == total {
			fmt.Printf("\rWriting output (%d/%d)...", i, total)
		}
	}
	fmt.Println() // New line after progress

	content += "}\n"

	// Determine output path based on current directory
	goPath := "data.go"
	if !fromPackageDir() {
		// Not in package directory, use full path
		goPath = "internal/data/specialty/data.go"
	}
	// nolint:gosec // G306: generated data.go must stay group-readable for the repo
	return os.WriteFile(goPath, []byte(content), 0644)
}

func writeTSOutput(data *OutputData) error {
	content := fmt.Sprintf(`// Code generated; DO NOT EDIT.
// Generated at: %s

export interface SpecialtyNode {
  nuccCode: string;
  iscoCode: string;
  label: string;
  domainSignature: string[];
}

export type ProximityTable = Record<string, Record<string, number>>;

export interface SpecialtyIndex {
  proximity: ProximityTable;
  specialties: Record<string, SpecialtyNode>;
}
`, data.GeneratedAt)

	// Determine TypeScript output path based on current directory
	tsPath := "src/types/specialty-ontology.ts"
	if fromPackageDir() {
		// Running from the package dir (go generate cwd) -> project root is three levels up
		tsPath = "../../../src/types/specialty-ontology.ts"
	}
	// nolint:gosec // G306: generated specialty-ontology.ts must stay group-readable for the repo
	return os.WriteFile(tsPath, []byte(content), 0644)
}

// now returns current time in ISO format.
func now() string {
	return time.Now().UTC().Format(time.RFC3339)
}
