// Package proximity provides pre-computed proximity data between specialty codes.
//
// Code generated by go:generate; DO NOT EDIT.
package proximity

// Table maps specialty pairs to their proximity scores.
type Table map[string]map[string]float64

// Generated contains the pre-computed proximity data, populated by init()
// functions in shard files.
var Generated = Table{}
