name: Build
on:
  workflow_call:
    inputs:
      API_URL:
        type: string
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - 20.16
        os:
        - ubuntu-latest
    steps:
      # Prepare Repository
      - name: Prepare
        uses: actions/checkout@v3
      # Setup Only If Using Event Reusable Workflows
      - name: Set Up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.java-version }}
          # registry-url: ${{ inputs.NPM_REGISTRY }}
          cache: npm
          # always-auth: true
          check-latest: false


      - name: Installing Packages
        run: npm install


      - name: Disable Next.js telemetry
        run: |
          echo "NEXT_TELEMETRY_DISABLED=1" >> $GITHUB_ENV

      - name: Build Packages
        run: |
          if [ -f yarn.lock ]; then yarn run build; \
          elif [ -f package-lock.json ]; then npm run build; \
          elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
          else echo "Lockfile not found." && exit 1; \
          fi
        env:
          NEXT_PUBLIC_API_URL: ${{ inputs.API_URL }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            .next
            public
          retention-days: 1