name: Dependabot CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/package.json'
      - '**/package-lock.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Only run on dependabot PRs
    if: github.actor == 'dependabot[bot]'

    strategy:
      matrix:
        node-version: [24.x]  # Specific version matching project's Node.js requirement

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
