name: Docker
on:
  workflow_call:
    inputs:
      USERNAME:
        type: string
        required: true
        default: admin
      API_URL:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      GIT_COMMIT:
        type: string
        required: true
      TAG:
        type: string
        required: true
      AUTHOR:
        type: string
        required: true
#       BUILD_TIME:
#         type: string
#         required: true

    secrets:
      PASSWORD:
        required: true
jobs:
  docker:
    name: Docker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
    steps:
    - name: Prepare
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: repository.konsulin.care
        username: ${{ inputs.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Get sha short
      id: tags
      run: |
        echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

    - name: Get Branch
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV


    - name: Build
      run: >-
        docker
        build
        -t repository.konsulin.care/repository/private/fe-konsulin:sha-${{ env.BRANCH }}-${{ steps.tags.outputs.sha_short }}
        -f docker/Dockerfile-ci
        --build-arg API_URL=${{ inputs.API_URL }}
        --build-arg VERSION=${{ inputs.VERSION }}
        --build-arg GIT_COMMIT=${{ inputs.GIT_COMMIT }}
        --build-arg TAG=${{ inputs.TAG }}
        --build-arg BUILD_TIME=${{ inputs.BUILD_TIME }}
        --build-arg AUTHOR=${{ inputs.AUTHOR }}
        .

#       with:
#         API_URL: ${{ inputs.API_URL }}
#         VERSION: ${{ inputs.VERSION }}
#         GIT_COMMIT: ${{ steps.tags.outputs.sha_short }}
#         TAG: sha-${{ env.BRANCH }}-${{ steps.tags.outputs.sha_short }}
#         BUILD_TIME: $(date)
#         AUTHOR: ${{ inputs.AUTHOR }}

    - name: Push sha-${{ steps.tags.outputs.sha_short }}
      run: >-
        docker
        push
        repository.konsulin.care/repository/private/fe-konsulin:sha-${{ env.BRANCH }}-${{ steps.tags.outputs.sha_short }}
