name: Docker (self-hosted)

on:
  workflow_call:
    inputs:
      AUTHOR:
        type: string
        required: true
      VERSION:
        type: string
        required: true
      GIT_COMMIT:
        type: string
        required: true
      BUILD_TIME:
        type: string
        required: true
      RUN_NUMBER:
        type: string
        required: true
      RELEASE_TAG:
        type: string
        required: true
      DOCKER_TAG:
        type: string
        required: true
      DOCKERFILE:
        type: string
        required: true
      API_URL:
        type: string
        required: true

jobs:
  docker:
    name: Docker (self-hosted)
    runs-on: self-hosted

    steps:
    - name: Prepare
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build Image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build -t konsulin/fe-service:${{ inputs.DOCKER_TAG }} -f ${{ inputs.DOCKERFILE }} . \
        --build-arg API_URL=${{ inputs.API_URL }}
        --build-arg VERSION=${{ inputs.VERSION }}
        --build-arg GIT_COMMIT=${{ inputs.GIT_COMMIT }}
        --build-arg TAG=${{ inputs.RELEASE_TAG }}
        --build-arg AUTHOR=${{ inputs.AUTHOR }}
        --build-arg RUN_NUMBER=${{ inputs.RUN_NUMBER }}
        --build-arg BUILD_TIME=${{ inputs.BUILD_TIME }}
