name: Build and Release Production

on:
  release:
    types: [created]
jobs:
  docker:
    name: Containerization
    uses: ./.github/workflows/docker-self-hosted.yml
    with:
      API_URL: https://api.konsulin.care
      VERSION: production
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      AUTHOR: ${{ github.actor }}
      GIT_COMMIT: ${{ github.sha }}
      RUN_NUMBER: ${{ github.run_number }}
      BUILD_TIME: $(date '+%Y-%m-%d_%H:%M:%S_%z')
      DOCKER_TAG: ${{ github.event.release.tag_name }}
      NODE_MODULES_CACHE_DIR: /tmp/${{ github.repository }}/production/node_modules
      NEXTJS_CACHE_DIR: /tmp/${{ github.repository }}/production/.next/cache

  deploy:
    name: Deployment
    needs: [docker]
    uses: ./.github/workflows/deploy-ansible.yml
    with:
      DOCKER_TAG: ${{ github.event.release.tag_name }}
      ANSIBLE_PLAYBOOK: playbook-prod.yml
      ANSIBLE_INVENTORY_HOSTS: "37.27.46.214,"
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
