name: Production
on:
  workflow_dispatch:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  docker:
    name: Containerization
    uses: ./.github/workflows/docker.yml
    needs:
    - build
    with:
      API_URL: https://app.konsulin.care
      VERSION: production
      TAG: $(git describe --tags --abbrev=0)
      AUTHOR: ${{ github.actor }}
      GIT_COMMIT: ${{ github.sha }}
      RUN_NUMBER: ${{ github.run_number }}
      BUILD_TIME: $(date '+%Y-%m-%d_%H:%M:%S_%z')
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
  deploy:
    name: Deployment
    uses: ./.github/workflows/deploy.yml
    needs:
    - docker
    with:
      ENVIRONMENT: production
      SERVICE_NAME: prod-app
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

