name: Trigger Coolify Deploy

on:
  workflow_call:
    secrets:
      COOLIFY_TRIGGER_URL:
        required: true
      COOLIFY_TOKEN:
        required: true

jobs:
  trigger-coolify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          echo "Triggering Coolify deployment..."
          curl "${{ secrets.COOLIFY_TRIGGER_URL }}" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"