name: Trigger Coolify Deploy

on:
  workflow_call:
    secrets:
      COOLIFY_URL:
        required: true
      COOLIFY_SERVICE:
        required: true
      COOLIFY_TOKEN:
        required: true

jobs:
  trigger-coolify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          echo "Triggering Coolify deployment..."
          curl -X POST "${{ secrets.COOLIFY_URL }}/services/${{ secrets.COOLIFY_SERVICE }}/restart?latest=true" \
            --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
